##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by DevCetra.com & contributors. The use of this
## source code is governed by an MIT-style license described in the LICENSE
## file located in this project's root directory.
##
## See: https://opensource.org/license/mit
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_widgets
description: A collection of practical widgets that are neither material nor cupertino.
version: 0.1.7
repository: https://github.com/DevCetra/df_widgets
funding:
  - https://www.buymeacoffee.com/robmllze
topics:
  - design
  - modular
  - theme
  - user-interface
  - widgets

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  flutter:
    sdk: flutter

  df_color: ^0.1.3
  df_di: ^0.9.3
  df_generate_dart_models_core: ^0.8.11
  df_pod: ^0.14.10
  df_scalable: ^0.7.1
  df_debouncer: ^0.2.4

  fluentui_system_icons: ^1.1.260
  visibility_detector: ^0.4.0+2

## -----------------------------------------------------------------------------

dev_dependencies:
  flutter_lints: ^5.0.0
